### ISSUE TITLE
Demo link is pointing to preact hint and not calendar

### ISSUE THREAD

**Issue by 99bits** [rschristian/preact-github-calendar#5]
Hi Christian,

Thanks for the calendar project, Demo is pointing to preact hint and not calendar.
Do you have the working link?

Cheers

**Comment by rschristian** [comment]
(Ryan, actually)

Ah shoot, the link in the ReadMe? I'll correct that right now. 

In the "About" sidebar, there's a link to the correct demo: https://preact-gh-calendar.rschristian.dev/

I really appreciate the heads up, thanks!

Edit: Should be corrected now
